### PR TITLE
Port econfee from upstream

### PR DESCRIPTION
**Pull request by rkfg**
Here are two changes that I decided to bundle into one PR.

1) I ported and slightly changed the `--econ-fee` flag from upstream.

This flag allows to rebalance without losing sats, the fee limit is calculated from the target channel fee. However, I made one change because for me the original algorithm is too strict so I can't rebalance at all. The upstream version calculates the total fee as `route fee` (what you actually pay) + `missing fee` (the fee of the outbound channel) + `future fee` (the fee of the incoming channel).

The author assumes that you should pay less (`rebalance fee` + `missing fee`) than `future fee`. It suggests that you should only rebalance if you will profit from both incoming and outgoing channels. I find it to be a rare case, more often than not I have to add liquidity to one popular channel so it allows payments to go through. I can't afford waiting for a payment in the opposite direction so that channel rebalances itself and pays me in the process. So I'm fine with spending a part of the earned fees on rebalance but no more than that.

In the end I dropped the `missing fee` part and now basically the check is `routing fees` should be less or equal than `future fees` (outgoing fees of the target channel). I realize it might be less reasonable for big routing nodes that process payments in both ways and want to maximize their profits. If that's the case it would be trivial to make this missing fee optional.

I also fixed the channel policy function, in upstream the author requests **the entire graph** and then iterates **all channels** to find the required one. I replaced this ridiculous approach with the respective API call.

2) `-f 0` and `-t 0` are now supported.

In this case the source/target channel is picked at random out of all channels that were selected according to the ratio policy. The rationale here is that sometimes when you automatically rebalance, `-f 1`, for example, picks the same channel every time and it can't be rebalanced at all (because of high fees/no routes). Other channels are never tried. I rebalance in N rounds, 50000 sats each time, first with `-f 1` and then `-t 1` and I had this issue before. Now I do the same with `-f 0` and then `-t 0` and it's much better as all channels have a chance.

### CODE REVIEW

**Comment by C-Otto** [comment]
>  It suggests that you should only rebalance if you will profit from both incoming and outgoing channels. I find it to be a rare case, more often than not I have to add liquidity to one popular channel so it allows payments to go through. I can't afford waiting for a payment in the opposite direction so that channel rebalances itself and pays me in the process.

I think this is a misunderstanding. The computation assumes that you'll forward every single satoshi that you have, in any channel, at the respective fee rate. If you have 100k sat in some channel with a fee rate of 100ppm, the script assumes that this (if you just wait long enough) will give you 10sat in fees. As such, taking these 100k sat out of the channel makes it impossible for you to earn the 10sat in fees. If you don't think that earning fees is realistic for the (source) channel, you should just decrease the fee rate (to 0ppm?).

>  I replaced this ridiculous approach with the respective API call.

I appreciate a bug report, pull request, or just a note somewhere. In this case I wasn't aware of how ridiculous my code was, and I fixed it by chance (without looking at your repository).

**Comment by C-Otto** [comment]
> Now I do the same with -f 0 and then -t 0 and it's much better as all channels have a chance.

I recommend only specifying the target channel (`-t -1` in the upstream repo to pick a random target channel). This way the script will consider all other channels as source channels, and quickly ignore channels that are too expensive based on the "econ fee" logic. In theory `-f -1` would give the same results, but it will take longer (as no up-front "mass ignore" is possible).

FYI: I'm not a fan of rebalancing all channels as some of those channels might be new (and not worth it!), and others might have fee rates that are unrealistic. On my node I have a specific list of channels/peers where auto-rebalancing is enabled.

**Comment by rkfg** [comment]
No, that wasn't a misunderstanding, I explained why I think this constraint should be relaxed. From my experience many channels are unidirectional so I find it more useful to refill the drained ones and get inbound liquidity in the others. I would wait for weeks for those channels to do the same by themselves losing opportunity of routing the payments in the main direction. So if I can rebalance them to provide that liquidity not at a loss I want to be able to do it. If your channels move money in both directions you don't need to rebalance them at all! Setting the fee to zero doesn't feel right though it's an interesting idea.

**Comment by C-Otto** [comment]
I still think there's a misunderstanding, or at least confusion on my side :) If you have drained channels, those are the targets (`-t`). I think we're clear on this part. The other side, the ones where you want inbound liquidity and where you'd have to wait weeks for that to happen: those are the source channels (`-f`). I simply propose to lower the fee rates of the source channels, to encourage others to send funds to the remote side. This also lowers the costs computed as part "econ fee", effectively helping you to use those channels as sources without specifying them manually. If you have a look at my node, there are a few channels with 10ppm (and some with 0ppm), and in fact these are used quite a lot for my rebalance transactions.

**Comment by accumulator** [comment]
Lowering fees on low activity mostly-local channels to induce routing might work, although I haven't seen this happen myself. I think lowering fees is also at odds with pricing the liquidity you provide, so it might be better to close and re-open that liquidity to another node.

Either way, I don;t really have a strong opinion in the above discussion, and I think it is good to leave it up to the user to decide how to go about it. 

I think this PR is an improvement to current master, regardless.

**Comment by accumulator** [comment]
That said and done, I think there's nice improvements both in @C-Otto upstream and my/@rkfg fork. So far I haven't really considered posting an upstream PR since my patches were more a personal/quick&dirty/worksforme quality level, but maybe we could investigate if and how we can merge these two diverging forks together?

**Comment by rkfg** [comment]
Would be good! I prefer this output style, it's pretty and more informative. I don't know how hard it would be to port the changes to the upstream though and I'm not a fan of Python in general so I'll leave it to the more passionate people.

> Lowering fees on low activity mostly-local channels to induce routing might work, although I haven't seen this happen myself.

Same, after I set the fees to 0 all I saw is forwarding between the channels that have close to no inbound liquidity. They were both at about 98% so only very small payments went through them. It was never the expected outcome where inbound channel is one of the more balanced ones and outbound is that with zero fee. So I routed for free and haven't achieved my goal. Fee motivation seems to be either not working at all or working only under certain circumstances for the most successful nodes. I went back to static fees in the end. Rebalancing works best when you know your future earnings in advance and the missed opportunity fee doesn't exist, at least for me. If you expect the balance to move in the desired direction and ready to wait you don't need rebalancing at all. In my case no matter how long I wait it just doesn't happen. If my case is an exception somebody else can easily port the remaining couple of lines and add a flag to enable that behavior.

**Pull request merged**
